spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wf1994429
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true #方便调试
  rabbitmq:
    host: localhost
    port: 5672
    username: ruoli
    password: wf1994429    
